name: Test Python code
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          cd python-challenges
          docker compose -f docker-compose.yml run --rm app pytest
